services:
  # Cloudflare Tunnel to allow secure hosting of PocketID behind Cloudflare with WAF + reverse proxy and no inbound firewalls rules required
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<Cloudflare-Tunnel-Token-from-Dashboard>
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    container_name: pocket-id
    restart: unless-stopped
    env_file: .env
    ports:
      - 1411:1411
    volumes:
      - "./data:/app/data"
    # Optional healthcheck built-into Pocket-ID
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
  # Optional containrrr/watchtower container to automatically update Docker base images. NOTE: Deprecated project as of 12/17/25
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: always
    environment:
      - DOCKER_API_VERSION=1.44
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
